### ISSUE TITLE
Limit Description to 500 words

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/Library-Search-Engine#1]
Ensure that the search results only display book descriptions truncated to the first 500 words or less.

**Comment by Manvith-M-Nayak** [comment]
Can I be assigned?

**Comment by jhalak-n** [comment]
hi can you please assign this to me?

**Comment by devanshishukla17** [comment]
can you assign me this

**Comment by nikhila-kuchimanchi** [comment]
!assign @Manvith-M-Nayak

**Comment by nikhila-kuchimanchi** [comment]
@Manvith-M-Nayak would you like more time to work on the issue?

**Comment by nikhila-kuchimanchi** [comment]
!extend 30

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Manvith-M-Nayak

**Comment by Manvith-M-Nayak** [comment]
> @Manvith-M-Nayak would you like more time to work on the issue?

In the readme, there is no app.py . Did you mean frontend.py?

**Comment by nikhila-kuchimanchi** [comment]
@Manvith-M-Nayak Yes, sorry for the confusion

**Comment by aryanmittal2107** [comment]
can i be assigned to this please

**Comment by SavvyHex** [comment]
Hey, can I get assigned to this?

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by SavvyHex** [comment]
Can I be assigned to this?
