### ISSUE TITLE
Improve Tokenization Efficiency

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/Library-Search-Engine#2]
Optimize the spacy_tokenizer function to handle edge cases where the input contains special characters or non-ASCII text. Implement checks to handle such cases before tokenizing.

**Comment by ShadowMarty** [comment]
Can you please assign me this @nikhila-kuchimanchi

**Comment by nikhila-kuchimanchi** [comment]
@ShadowMarty you can only be assigned one issue at a time, kindly finish the first issue assigned then request this issue afterwards

**Comment by Gekkouga77** [comment]
Hey there! Could you please assign this to me? @nikhila-kuchimanchi

**Comment by PandaTGOS** [comment]
Hey can I get assigned to this  @nikhila-kuchimanchi

**Comment by nikhila-kuchimanchi** [comment]
!assign @PandaTGOS

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @PandaTGOS 60

**Comment by PandaTGOS** [comment]
Heyy I was done with this issue
can I get deassigned ? @nikhila-kuchimanchi

**Comment by PandaTGOS** [comment]
!withdraw

**Comment by nikhila-kuchimanchi** [comment]
@PandaTGOS did you submit a pull request?
