### ISSUE TITLE
Create a Log-in Page and Implement User Authentication

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/Library-Search-Engine#4]
Develop a user authentication system to allow users to create accounts, save searches, and view search history.

Please update the README.md file to reflect the latest additions and improvements made, following the format already provided in the README

**Comment by Viprakshi** [comment]
can you assign me this?

**Comment by ShadowMarty** [comment]
Can you please assign this issue @nikhila-kuchimanchi

**Comment by nikhila-kuchimanchi** [comment]
!assign @ShadowMarty

**Comment by mahika34** [comment]
can u pls assign me?

**Comment by nikhila-kuchimanchi** [comment]
@manikyabard only one person can be assigned an issue at a time

**Comment by ShadowMarty** [comment]
Can you please provide the requirements.txt file with the dependencies versions. Its throwing errors while installing them:

INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached scipy-1.11.2-cp312-cp312-win_amd64.whl.metadata (59 kB)
  Using cached scipy-1.11.1.tar.gz (56.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      + meson setup C:\Users\irons\AppData\Local\Temp\pip-install-glt76o0a\scipy_ab12ae870c834ef4bc9120835b1a5da7 C:\Users\irons\AppData\Local\Temp\pip-install-glt76o0a\scipy_ab12ae870c834ef4bc9120835b1a5da7\.mesonpy-4px1mt3d\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\irons\AppData\Local\Temp\pip-install-glt76o0a\scipy_ab12ae870c834ef4bc9120835b1a5da7\.mesonpy-4px1mt3d\build\meson-python-native-file.ini
      The Meson build system
      Version: 1.5.2
      Source dir: C:\Users\irons\AppData\Local\Temp\pip-install-glt76o0a\scipy_ab12ae870c834ef4bc9120835b1a5da7
      Build dir: C:\Users\irons\AppData\Local\Temp\pip-install-glt76o0a\scipy_ab12ae870c834ef4bc9120835b1a5da7\.mesonpy-4px1mt3d\build
      Build type: native build
      Project name: SciPy
      Project version: 1.11.1
      C compiler for the host machine: gcc (gcc 6.3.0 "gcc (MinGW.org GCC-6.3.0-1) 6.3.0")
      C linker for the host machine: gcc ld.bfd 2.28
      C++ compiler for the host machine: c++ (gcc 6.3.0 "c++ (MinGW.org GCC-6.3.0-1) 6.3.0")
      C++ linker for the host machine: c++ ld.bfd 2.28
      Cython compiler for the host machine: cython (cython 0.29.37)
      Host machine cpu family: x86
      Host machine cpu: x86
      Program python found: YES (C:\Users\irons\hacknight\venv\Scripts\python.exe)
      Need python for x86, but found x86_64
      Run-time dependency python found: NO (tried sysconfig)

      ..\..\meson.build:24:14: ERROR: Python dependency not found

      A full log can be found at C:\Users\irons\AppData\Local\Temp\pip-install-glt76o0a\scipy_ab12ae870c834ef4bc9120835b1a5da7\.mesonpy-4px1mt3d\build\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by nikhila-kuchimanchi** [comment]
@ShadowMarty making the requirements.txt file is a separate issue in the repo with 150 points assigned to it. Work on that issue before attempting this. I will deassign you from this issue, request to work on that then I will assign to you to this issue once it's done.

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
@ShadowMarty request to work on the requirements.txt file

**Comment by ShadowMarty** [comment]
Can you please assign me the issue to implement requirements.txt @nikhila-kuchimanchi

**Comment by nikhila-kuchimanchi** [comment]
@ShadowMarty done

**Comment by MeghanaK11** [comment]
can you assign me to this

**Comment by Ayush-jk** [comment]
can i be assigned to this

**Comment by mahika34** [comment]
can i be assigned

**Comment by nikhila-kuchimanchi** [comment]
!assign @mahika34

**Comment by ShadowMarty** [comment]
@nikhila-kuchimanchi I have implemented requirements.txt but dont have access to push the code

**Comment by PandaTGOS** [comment]
Hey can I get assigned to this ?

**Comment by ShadowMarty** [comment]
@nikhila-kuchimanchi Can you please assign me this issue, I had asked earlier and was redirected to requirements.txt which i have implemented now

**Comment by devanshishukla17** [comment]
can I get assigned to this please

**Comment by nikhila-kuchimanchi** [comment]
!assign @ShadowMarty

**Comment by srijan-nodes** [comment]
if its empty can I get this?

**Comment by KaparthyReddy** [comment]
Kindly assign this.

**Comment by ShadowMarty** [comment]
@nikhila-kuchimanchi Is the main repo up to date with other issues implemented, I would like to have the latest version before I work on the frontend

**Comment by nikhila-kuchimanchi** [comment]
@srujandeshpande @KaparthyReddy someone has already been assigned to this issue

**Comment by nikhila-kuchimanchi** [comment]
@ShadowMarty yes it is up-to-date

**Comment by ShadowMarty** [comment]
Thank you @nikhila-kuchimanchi , am forking repo now, have some basic front end ready, 
could you also please clarify what could i use to implement authentication system, a mysql database or any specific preferences

**Comment by Git-Cat-21** [comment]
can i be assigned to this

**Comment by SamridhiShreyaa** [comment]
can i be assigned?

**Comment by nikhila-kuchimanchi** [comment]
@ShadowMarty you can use mysql or django for authentication

**Comment by AkshayaR11** [comment]
can i get assigned to this??

**Comment by Advaith2805** [comment]
Can I get assigned to this

**Comment by nikhila-kuchimanchi** [comment]
!assign @ShadowMarty

**Comment by AutisticCoder-9000** [comment]
May I kindly get assigned this task?

**Comment by Anyaaa-2** [comment]
can i get assigned to this

**Comment by ShadowMarty** [comment]
@nikhila-kuchimanchi I have created a PR with the the login, register pages along with MySQL based authentication, please do let me know your thoughts, if it meets your expectations

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by Hemz1416** [comment]
can i get assigned to this @nikhila-kuchimanchi
