### ISSUE TITLE
requirements.txt is missing

### ISSUE THREAD

**Issue by gsd-sam** [acmpesuecc/Library-Search-Engine#5]
It is not possible to install the required packages via `pip install -r requirements.txt` as the file is missing.

**Comment by Anyaaa-2** [comment]
can i get assigned

**Comment by ShadowMarty** [comment]
Can you please assign me this issue, I was redirected to work on this first @nikhila-kuchimanchi

**Comment by nikhila-kuchimanchi** [comment]
!assign @ShadowMarty

**Comment by mahika34** [comment]
can i be assigned?

**Comment by ShadowMarty** [comment]
@nikhila-kuchimanchi   I have implemented the requirements.txt but I have no access rights to push the code right now, can you please reassign

**Comment by sujith27pes** [comment]
can i be assigned?

**Comment by sujith27pes** [comment]
can i be assigned @sujith27pes

**Comment by mahika34** [comment]
can i be assigned?

**Comment by nikhila-kuchimanchi** [comment]
!assign @sujith27pes

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
@ShadowMarty sorry for the delay I'll assign it to you now

**Comment by mahika34** [comment]
can u assign me?

**Comment by nikhila-kuchimanchi** [comment]
!assign @ShadowMarty

**Comment by sujith27pes** [comment]
can i be assigned? I have the requirements.txt with me

**Comment by nikhila-kuchimanchi** [comment]
@ShadowMarty was assigned to the issue first, i'll look over their code and if it is not satisfactory then i will assign it to you @sujith27pes

**Comment by ShadowMarty** [comment]
Why am I not able to push the code

PS C:\Users\irons\hacknight\Library-Search-Engine> git push
ERROR: Permission to acmpesuecc/Library-Search-Engine.git denied to ShadowMarty.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by nikhila-kuchimanchi** [comment]
@ShadowMarty please contact a mentor for git support

**Comment by ShadowMarty** [comment]
@nikhila-kuchimanchi I have created a pull request, its not able to automatically resolve merge conflicts

**Comment by ShadowMarty** [comment]
Could you please look into the changes and suggest what I may do next

**Comment by nikhila-kuchimanchi** [comment]
@ShadowMarty request has been closed, you have been assigned the points for this issue

**Comment by ShadowMarty** [comment]
thank you, am ready to work on the login page and authentication system now

**Comment by nikhila-kuchimanchi** [comment]
!deassign
